cppstring = ('std::string', 'string')

traits2cpp = {
 #'All',
 #'Any',
 #'BaseDescriptor',
 'Bool': 'bool',
 #'Bunch',
 #'Bytes',
 'CBool': 'bool',
 #'CBytes',
 'CComplex': 'std::complex',
 'CFloat': 'double',
 'CInt': 'int',
 'CLong': 'std::size_t',
 #'CRegExp',
 'CUnicode': cppstring,
 #'CaselessStrEnum',
 #'ClassBasedTraitType',
 #'ClassTypes',
 'Complex': 'std::complex',
 #'Container',
 #'DefaultHandler',
 'Dict': 'std::map',
 #'DottedObjectName',
 'Enum': 'enum',
 #'EventHandler',
 'Float': 'double',
 #'ForwardDeclaredInstance',
 #'ForwardDeclaredMixin',
 #'ForwardDeclaredType',
 #'HasDescriptors',
 #'HasTraits',
 #'Instance',
 'Int': 'int',
 'Integer': 'int',
 'List': ('std::list', 'list'),
 'Long': 'std::size_t',
 #'MetaHasDescriptors',
 #'MetaHasTraits',
 #'NoDefaultSpecified',
 #'ObjectName',
 #'ObserveHandler',
 #'Sentinel',
 #'SequenceTypes',
 'Set': 'std::set',
 #'TCPAddress',
 #'This',
 #'TraitError',
 #'TraitType',
 'Tuple': 'std::tuple',
 #'Type',
 #'Undefined',
 'Unicode': cppstring,
 'Union': 'union',
 #'UseEnum',
 #'ValidateHandler',
}